import type { Metadata } from "next";
import "./globals.css";
import { Martel_Sans } from "next/font/google";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const martelSans = Martel_Sans({
  weight: ["200", "300", "400", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const netflixSans = localFont({
  src: [
    {
      path: "../public/assets/fonts/netflix-sans/NetflixSans-Light.otf",
      weight: "300",
    },
    {
      path: "../public/assets/fonts/netflix-sans/NetflixSans-Regular.otf",
      weight: "400",
    },
    {
      path: "../public/assets/fonts/netflix-sans/NetflixSans-Medium.otf",
      weight: "500",
    },
    {
      path: "../public/assets/fonts/netflix-sans/NetflixSans-Medium.otf",
      weight: "500",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-black ${netflixSans.className}`}>{children}</body>
    </html>
  );
}
